/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BanContBoLeft: typeof import('./components/bannerContent/banContbottom/banContBoLeft.vue')['default']
    BanContBoRight: typeof import('./components/bannerContent/banContbottom/banContBoRight.vue')['default']
    BanContbottom: typeof import('./components/bannerContent/banContbottom/banContbottom.vue')['default']
    BanContNav: typeof import('./components/bannerContent/banContbottom/banContNav.vue')['default']
    BannerContent: typeof import('./components/bannerContent/bannerContent.vue')['default']
    BannerTop: typeof import('./components/bannerTop/bannerTop.vue')['default']
    BannerTopContent: typeof import('./components/bannerTopContent/bannerTopContent.vue')['default']
    DrawerBanner: typeof import('./components/drawerbanner1/DrawerBanner.vue')['default']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Exeact: typeof import('./components/banner1/exeact.vue')['default']
    IEpTools: typeof import('~icons/ep/tools')['default']
    LoginIndex: typeof import('./components/Login/LoginIndex.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
